"""add role_routing table

Revision ID: 12fd22dfa30e
Revises: bb781bdb383b
Create Date: 2026-10-01 09:10:24.176884

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12fd22dfa30e"
down_revision: str | Sequence[str] | None = "bb781bdb383b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_routing",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("min_severity", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role", "channel", name="uq_role_routing_role_channel"),
    )
    with op.batch_alter_table("role_routing", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_routing_channel"), ["channel"], unique=False)
        batch_op.create_index(batch_op.f("ix_role_routing_role"), ["role"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role_routing", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_routing_role"))
        batch_op.drop_index(batch_op.f("ix_role_routing_channel"))

    op.drop_table("role_routing")
    # ### end Alembic commands ###
