"""add driver_annotations table

Revision ID: 1fbabccf84df
Revises: 940bfb427cd4
Create Date: 2026-10-04 16:30:59.805396

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fbabccf84df"
down_revision: str | Sequence[str] | None = "940bfb427cd4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver_annotations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("driver_id", sa.String(length=50), nullable=False),
        sa.Column("scope_county", sa.String(length=100), nullable=True),
        sa.Column("scope_pathogen", sa.String(length=100), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("driver_annotations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_driver_annotations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_driver_annotations_driver_id"), ["driver_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_driver_annotations_scope_county"), ["scope_county"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_driver_annotations_scope_pathogen"), ["scope_pathogen"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("driver_annotations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_driver_annotations_scope_pathogen"))
        batch_op.drop_index(batch_op.f("ix_driver_annotations_scope_county"))
        batch_op.drop_index(batch_op.f("ix_driver_annotations_driver_id"))
        batch_op.drop_index(batch_op.f("ix_driver_annotations_created_at"))

    op.drop_table("driver_annotations")
    # ### end Alembic commands ###
