"""add case events and close fields

Revision ID: 2f4b3912d922
Revises: df169f163b2a
Create Date: 2026-10-04 17:03:58.605558

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f4b3912d922"
down_revision: str | Sequence[str] | None = "df169f163b2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor_name", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("case_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_case_events_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_case_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_case_events_event_type"), ["event_type"], unique=False)

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("closed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("closed_by", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("closed_reason", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("closed_note", sa.Text(), nullable=True))
        batch_op.create_foreign_key("fk_cases_closed_by", "users", ["closed_by"], ["id"], ondelete="SET NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_constraint("fk_cases_closed_by", type_="foreignkey")
        batch_op.drop_column("closed_note")
        batch_op.drop_column("closed_reason")
        batch_op.drop_column("closed_by")
        batch_op.drop_column("closed_at")

    with op.batch_alter_table("case_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_case_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_case_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_case_events_case_id"))

    op.drop_table("case_events")
    # ### end Alembic commands ###
