"""add system_config and sector_taxonomy tables

Revision ID: 7999e8174cf7
Revises: f0a855e7a731
Create Date: 2026-10-04 05:29:10.993140

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7999e8174cf7"
down_revision: str | Sequence[str] | None = "f0a855e7a731"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sector_taxonomy",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raw_sector", sa.String(length=50), nullable=False),
        sa.Column("canonical_sector", sa.String(length=50), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.Column("display_label", sa.String(length=50), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sector_taxonomy", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sector_taxonomy_canonical_sector"), ["canonical_sector"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sector_taxonomy_raw_sector"), ["raw_sector"], unique=True)

    op.create_table(
        "system_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_config_key"), ["key"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_config_key"))

    op.drop_table("system_config")
    with op.batch_alter_table("sector_taxonomy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sector_taxonomy_raw_sector"))
        batch_op.drop_index(batch_op.f("ix_sector_taxonomy_canonical_sector"))

    op.drop_table("sector_taxonomy")
    # ### end Alembic commands ###
