"""add lab_requests table

Revision ID: 85d739b482ca
Revises: be4b2e3b3d01
Create Date: 2026-10-04 11:45:04.411867

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85d739b482ca"
down_revision: str | Sequence[str] | None = "be4b2e3b3d01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("result_notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("completed_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["completed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["record_id"], ["amr_isolate_records.record_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lab_requests_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_requests_record_id"), ["record_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_requests_requested_at"), ["requested_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_requests_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_requests_status"))
        batch_op.drop_index(batch_op.f("ix_lab_requests_requested_at"))
        batch_op.drop_index(batch_op.f("ix_lab_requests_record_id"))
        batch_op.drop_index(batch_op.f("ix_lab_requests_priority"))

    op.drop_table("lab_requests")
    # ### end Alembic commands ###
