"""add cases table and case_id FK on isolates

Revision ID: a75f0e971241
Revises: 7999e8174cf7
Create Date: 2026-10-04 06:01:33.628968

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a75f0e971241"
down_revision: str | Sequence[str] | None = "7999e8174cf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_code", sa.String(length=50), nullable=False),
        sa.Column("case_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("county", sa.String(length=100), nullable=False),
        sa.Column("sub_county", sa.String(length=100), nullable=True),
        sa.Column("sector", sa.String(length=20), nullable=True),
        sa.Column("species", sa.String(length=100), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("first_isolate_at", sa.DateTime(), nullable=True),
        sa.Column("latest_isolate_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_id"], ["sampling_sites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cases_case_code"), ["case_code"], unique=True)
        batch_op.create_index(batch_op.f("ix_cases_case_type"), ["case_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_county"), ["county"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_latest_isolate_at"), ["latest_isolate_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_sector"), ["sector"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_site_id"), ["site_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_status"), ["status"], unique=False)

    with op.batch_alter_table("amr_isolate_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("case_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_amr_isolate_records_case_id"), ["case_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_amr_isolate_records_case_id", "cases", ["case_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("amr_isolate_records", schema=None) as batch_op:
        batch_op.drop_constraint("fk_amr_isolate_records_case_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_amr_isolate_records_case_id"))
        batch_op.drop_column("case_id")

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_status"))
        batch_op.drop_index(batch_op.f("ix_cases_site_id"))
        batch_op.drop_index(batch_op.f("ix_cases_sector"))
        batch_op.drop_index(batch_op.f("ix_cases_latest_isolate_at"))
        batch_op.drop_index(batch_op.f("ix_cases_created_at"))
        batch_op.drop_index(batch_op.f("ix_cases_county"))
        batch_op.drop_index(batch_op.f("ix_cases_case_type"))
        batch_op.drop_index(batch_op.f("ix_cases_case_code"))

    op.drop_table("cases")
    # ### end Alembic commands ###
