"""add action_plans table

Revision ID: bb781bdb383b
Revises: df495d35f107
Create Date: 2026-10-01 08:47:39.257654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb781bdb383b'
down_revision: Union[str, Sequence[str], None] = 'df495d35f107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closing_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plans_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_sub_county'), ['sub_county'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plans_title'))
        batch_op.drop_index(batch_op.f('ix_action_plans_sub_county'))
        batch_op.drop_index(batch_op.f('ix_action_plans_status'))
        batch_op.drop_index(batch_op.f('ix_action_plans_source_type'))
        batch_op.drop_index(batch_op.f('ix_action_plans_source_id'))
        batch_op.drop_index(batch_op.f('ix_action_plans_priority'))
        batch_op.drop_index(batch_op.f('ix_action_plans_due_date'))
        batch_op.drop_index(batch_op.f('ix_action_plans_created_by'))
        batch_op.drop_index(batch_op.f('ix_action_plans_created_at'))
        batch_op.drop_index(batch_op.f('ix_action_plans_county'))
        batch_op.drop_index(batch_op.f('ix_action_plans_assigned_to'))

    op.drop_table('action_plans')
    # ### end Alembic commands ###
