"""add glass_reference_mappings table

Revision ID: be4b2e3b3d01
Revises: a75f0e971241
Create Date: 2026-10-04 07:10:24.465888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be4b2e3b3d01"
down_revision: str | Sequence[str] | None = "a75f0e971241"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "glass_reference_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mapping_type", sa.String(length=30), nullable=False),
        sa.Column("raw_value", sa.String(length=100), nullable=False),
        sa.Column("glass_code", sa.String(length=50), nullable=False),
        sa.Column("glass_label", sa.String(length=200), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mapping_type", "raw_value", name="uq_glass_mapping_type_value"),
    )
    with op.batch_alter_table("glass_reference_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_glass_reference_mappings_mapping_type"), ["mapping_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_glass_reference_mappings_raw_value"), ["raw_value"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("glass_reference_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_glass_reference_mappings_raw_value"))
        batch_op.drop_index(batch_op.f("ix_glass_reference_mappings_mapping_type"))

    op.drop_table("glass_reference_mappings")
    # ### end Alembic commands ###
