"""add SLA fields to lab_requests

Revision ID: df169f163b2a
Revises: 1fbabccf84df
Create Date: 2026-10-04 16:46:33.806328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df169f163b2a"
down_revision: str | Sequence[str] | None = "1fbabccf84df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("acknowledged_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("acknowledged_by", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("escalated_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("escalation_level", sa.Integer(), server_default="0", nullable=False))
        batch_op.create_index(
            batch_op.f("ix_lab_requests_acknowledged_at"), ["acknowledged_at"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_lab_requests_acknowledged_by", "users", ["acknowledged_by"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_requests", schema=None) as batch_op:
        batch_op.drop_constraint("fk_lab_requests_acknowledged_by", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_lab_requests_acknowledged_at"))
        batch_op.drop_column("escalation_level")
        batch_op.drop_column("escalated_at")
        batch_op.drop_column("acknowledged_by")
        batch_op.drop_column("acknowledged_at")

    # ### end Alembic commands ###
