"""add sampling_sites and site_id

Revision ID: f0a855e7a731
Revises: 12fd22dfa30e
Create Date: 2026-10-01 09:26:38.252122

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0a855e7a731"
down_revision: str | Sequence[str] | None = "12fd22dfa30e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sampling_sites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("site_type", sa.String(length=30), nullable=False),
        sa.Column("sector", sa.String(length=20), nullable=False),
        sa.Column("county", sa.String(length=100), nullable=False),
        sa.Column("sub_county", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("owner_name", sa.String(length=200), nullable=True),
        sa.Column("owner_contact", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sampling_sites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sampling_sites_county"), ["county"], unique=False)
        batch_op.create_index(batch_op.f("ix_sampling_sites_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sampling_sites_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_sampling_sites_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_sampling_sites_sector"), ["sector"], unique=False)
        batch_op.create_index(batch_op.f("ix_sampling_sites_site_type"), ["site_type"], unique=False)

    with op.batch_alter_table("amr_isolate_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("site_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_amr_isolate_records_site_id"), ["site_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_amr_isolate_records_site_id", "sampling_sites", ["site_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("amr_isolate_records", schema=None) as batch_op:
        batch_op.drop_constraint("fk_amr_isolate_records_site_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_amr_isolate_records_site_id"))
        batch_op.drop_column("site_id")

    with op.batch_alter_table("sampling_sites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sampling_sites_site_type"))
        batch_op.drop_index(batch_op.f("ix_sampling_sites_sector"))
        batch_op.drop_index(batch_op.f("ix_sampling_sites_name"))
        batch_op.drop_index(batch_op.f("ix_sampling_sites_is_active"))
        batch_op.drop_index(batch_op.f("ix_sampling_sites_created_at"))
        batch_op.drop_index(batch_op.f("ix_sampling_sites_county"))

    op.drop_table("sampling_sites")
    # ### end Alembic commands ###
